version: "3"

services:
  api-gateway:
    build:
      context: microservices/api-gateway
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    hostname: api-gateway
    ports:
      - "5000:5000"
    env_file:
      - microservices/api-gateway/.env
    networks:
      - backend
    depends_on:
      - rabbitmq
      - database
    links:
      - rabbitmq
      - database
    volumes:
      - ./microservices/api-gateway:/usr/src/app
      - /var/www/api-gateway/node_modules
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 192.168.29.38:24224
        tag: api-gateway
  media-rest:
    build:
      context: ./microservices/media-rest
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    hostname: media-rest
    ports:
      - "9001:9001"
    env_file:
      - ./microservices/media-rest/.env
    networks:
      - backend
    depends_on:
      - rabbitmq
      - database
    links:
      - rabbitmq
      - database
    volumes:
      - ./microservices/media-rest:/usr/src/app
      - /usr/src/app/node_modules
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 192.168.29.38:24224
        tag: media-rest
  media-processor:
    build:
      context: ./microservices/media-processor
      dockerfile: Dockerfile.dev
    hostname: media-processor
    ports:
      - "9002:9002"
    env_file:
      - ./microservices/media-processor/.env
    networks:
      - backend
    depends_on:
      - rabbitmq
      - database
    links:
      - rabbitmq
      - database
    volumes:
      - ./microservices/media-processor:/usr/src/app
      - ./microservices/media-processor/node_modules:/usr/src/app/node_modules
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 192.168.29.38:24224
        tag: media-processor
  client-app:
    build:
      context: ./microservices/client-app
      dockerfile: Dockerfile.dev
    hostname: client-app
    ports:
      - "3000:3000"
    env_file:
      - microservices/client-app/.env.local
    networks:
      - backend
    depends_on:
      - rabbitmq
      - database
    links:
      - rabbitmq
      - database
    volumes:
      - ./microservices/client-app:/usr/src/app
      - ./microservices/client-app/node_modules:/usr/src/app/node_modules
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 192.168.29.38:24224
        tag: client-app
  database:
    image: postgres:latest
    restart: on-failure
    container_name: postgres
    hostname: database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=master
      - POSTGRES_INITDB_ARGS="--auth-host=scram-sha-256"
      - DEBUG=true
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 192.168.29.38:24224
        tag: database
  rabbitmq:
    image: rabbitmq:3-management
    restart: on-failure
    container_name: rabbitmq
    hostname: rabbitmq
    volumes:
      - rabbit_data:/var/lib/rabbitmq
      - ./init/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend
    logging:
      driver: fluentd
      options:
        fluentd-async: "true"
        fluentd-address: 192.168.29.38:24224
        tag: rabbitmq
networks:
  backend:
    driver: bridge
volumes:
  pg_data:
    driver: local
  rabbit_data:
    driver: local
