import { config } from 'dotenv';

config();

const {
	RABBIT_MQ_HOST,
	RABBIT_MQ_PORT,
	RABBIT_MQ_QUEUE_NAME,
	RABBIT_MQ_USER,
	RABBIT_MQ_PASS,
	MAX_FILE_SIZE_MB,
	SUPPORTED_AUDIO_EXTENSIONS,
	SUPPORTED_IMAGE_EXTENSIONS,
	SUPPORTED_VIDEO_EXTENSIONS,
	SUPPORTED_OCR_LANGUAGES
} = process.env;

export {
	RABBIT_MQ_USER,
	RABBIT_MQ_PASS,
	RABBIT_MQ_HOST,
	RABBIT_MQ_PORT,
	RABBIT_MQ_QUEUE_NAME,
	MAX_FILE_SIZE_MB,
	SUPPORTED_AUDIO_EXTENSIONS,
	SUPPORTED_IMAGE_EXTENSIONS,
	SUPPORTED_VIDEO_EXTENSIONS,
	SUPPORTED_OCR_LANGUAGES,
}
