import { config } from 'dotenv';

config();

const {
	RABBIT_MQ_HOST,
	RABBIT_MQ_PORT,
	RABBIT_MQ_USER,
	RABBIT_MQ_PASS,
	MAX_FILE_SIZE_MB,
	SUPPORTED_AUDIO_EXTENSIONS,
	SUPPORTED_IMAGE_EXTENSIONS,
	SUPPORTED_VIDEO_EXTENSIONS,
	SUPPORTED_OCR_LANGUAGES,
	SUPPORTED_SPEECH_RECOGNITION_LANGUAGES,
	GCP_SPEECH_TO_TEXT_CREDENTIALS,
} = process.env;

export {
	RABBIT_MQ_USER,
	RABBIT_MQ_PASS,
	RABBIT_MQ_HOST,
	RABBIT_MQ_PORT,
	MAX_FILE_SIZE_MB,
	SUPPORTED_AUDIO_EXTENSIONS,
	SUPPORTED_IMAGE_EXTENSIONS,
	SUPPORTED_VIDEO_EXTENSIONS,
	SUPPORTED_OCR_LANGUAGES,
	SUPPORTED_SPEECH_RECOGNITION_LANGUAGES,
	GCP_SPEECH_TO_TEXT_CREDENTIALS,
}
